const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],notes=$('#notes'),conversation=$('#conversation');
// Reset the earlier test build once, then keep only chats created in this fresh version.
localStorage.removeItem('notequiz-study-chats-v1');
const KEY='notequiz-study-chats-v2';let chats=JSON.parse(localStorage.getItem(KEY)||'[]'),activeId=chats[0]?.id;
const save=()=>localStorage.setItem(KEY,JSON.stringify(chats)),active=()=>chats.find(c=>c.id===activeId),esc=t=>{const e=document.createElement('i');e.textContent=t;return e.innerHTML},sentences=t=>t.replace(/\s+/g,' ').split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim().replace(/[.]+$/,'')).filter(s=>s.length>20),phrase=s=>s.split(' ').slice(0,9).join(' ');
const noise=/\b(review seminar|presented by|guided by|department of|university|institute|academic year|copyright|references|publication plan|table of contents|\bindex\b)\b/i;
const core=/\b(problem|challenge|objective|aim|propose|method|approach|system|architecture|model|algorithm|result|evaluation|performance|benefit|advantage|limitation|conclusion|future|application|implement|dataset|analysis|experiment|accuracy|automated|semantic|transformer|vision)\b/gi;
function studySentences(text){return sentences(text).map((s,i)=>({s,i,score:(s.match(core)||[]).length*4+Math.min(s.split(/\s+/).length,35)/18-(noise.test(s)?9:0)})).filter(x=>x.score>0&&x.s.split(/\s+/).length>7)}
function selectTopics(text,count){const all=studySentences(text);const pool=all.length?all:sentences(text).map((s,i)=>({s,i,score:1}));if(!pool.length)return[];const bands=Math.min(count,pool.length),picked=[];for(let band=0;band<bands;band++){const start=Math.floor(band*pool.length/bands),end=Math.floor((band+1)*pool.length/bands),choice=[...pool.slice(start,end)].sort((a,b)=>b.score-a.score)[0];if(choice)picked.push(choice)}const seen=new Set(picked.map(x=>x.i));for(const item of [...pool].sort((a,b)=>b.score-a.score)){if(picked.length>=count)break;if(!seen.has(item.i)){picked.push(item);seen.add(item.i)}}return picked.sort((a,b)=>a.i-b.i).map(x=>x.s)}
function importantTerm(s){const words=s.replace(/[^a-zA-Z0-9 -]/g,'').split(/\s+/),candidates=words.filter(w=>w.length>6&&!/^(introduction|research|technology|management|engineering|department|presented|guided)$/i.test(w));const phrases=['semantic segmentation','vision transformers','problem statement','land plot','machine learning','deep learning','real time','manual methods'],found=phrases.find(p=>s.toLowerCase().includes(p));return found||candidates[Math.floor(candidates.length/2)]||words[0]}
function createChat(){const c={id:Date.now().toString(),title:'New study chat',source:'',messages:[]};chats.unshift(c);activeId=c.id;save();renderAll();notes.focus()}
function question(s,i,type){const topic=phrase(s),term=importantTerm(s);if(type==='true or false'||type==='mixed'&&i%3===2)return{q:`True or false: ${esc(s)}.`,a:`True — ${s}.`,o:''};if(type==='multiple choice'||type==='mixed'&&i%3===0)return{q:`Which statement best captures the important topic “${esc(topic)}”?`,a:`Correct answer: A. ${s}`,o:`<div class="options"><span>A. ${esc(s)}</span><span>B. It has no connection to the topic.</span><span>C. It is always the opposite.</span><span>D. The topic is never discussed.</span></div>`};if(type==='fill in the blank')return{q:`Fill in the blank: ${esc(s.replace(new RegExp(term,'i'),'________'))}.`,a:`Correct answer: “${term}”. Full idea: ${s}.`,o:''};if(type==='long answer')return{q:`Write a detailed answer explaining “${esc(topic)}”. Include the concept, significance, and an example or implication from the notes.`,a:`Expected answer: ${s}.`,o:''};return{q:`In your own words, explain this idea: ${esc(topic)}.`,a:`Expected answer: ${s}.`,o:''}}
function add(m){active().messages.push(m);save();renderConversation()}
function renderQuiz(m){const f=$('#quizTemplate').content.cloneNode(true),q=f.querySelector('.message');$('.quiz-lead',q).textContent=`Here’s your ${m.difficulty.toLowerCase()} quiz — ${m.count} high-priority questions sampled across the full document.`;$('.quiz-list',q).innerHTML=m.questions.map((x,i)=>`<div class="question"><span class="q-number">${i+1}.</span>${x.q}${x.o}</div>`).join('');const a=$('.answers',q);a.innerHTML=`<strong>Answer key</strong>${m.questions.map((x,i)=>`<div><strong>${i+1}.</strong> ${esc(x.a)}</div>`).join('')}`;a.hidden=false;$('.reveal',q).textContent='Hide answers';$('.quiz-bubble',q).classList.add('solved');$('.reveal',q).onclick=e=>{a.hidden=!a.hidden;e.target.textContent=a.hidden?'Show answers':'Hide answers';$('.quiz-bubble',q).classList.toggle('solved',!a.hidden)};$('.try-again',q).onclick=quiz;conversation.append(f)}
function renderConversation(){const c=active();conversation.innerHTML=`<article class="message bot intro"><div class="avatar">✦</div><div class="bubble"><p>${c.source?'Your notes are loaded. Ask a follow-up question, or generate another quiz.':'Hi! I’m NoteQuiz. Add a notes file or paste notes below and I’ll make a focused quiz.'}</p><p class="subtle">Your study chat and notes are saved in this browser.</p></div></article>`;c.messages.forEach(m=>{if(m.kind==='quiz')return renderQuiz(m);const e=document.createElement('article');e.className='message';if(m.kind==='user'){e.style.marginLeft='44px';e.innerHTML=`<div class="bubble" style="background:#6049d8;color:white;border-radius:15px 4px 15px 15px"><p>${esc(m.text)}</p></div>`}else e.innerHTML=`<div class="avatar">✦</div><div class="bubble"><p>${esc(m.text)}</p></div>`;conversation.append(e)});conversation.scrollTop=conversation.scrollHeight}
function reply(q){const words=q.toLowerCase().match(/[a-z]{4,}/g)||[],ranked=sentences(active().source).map(s=>({s,n:words.filter(w=>s.toLowerCase().includes(w)).length})).sort((a,b)=>b.n-a.n);return !ranked[0]?.n?'I can answer only from the notes in this study chat. Try naming a term from the material, or add more notes.':`Based on your notes: ${ranked.slice(0,2).map(x=>x.s).join(' ')}`}
function quiz(){const c=active(),input=notes.value.trim();if(input&&!c.source){c.source=input;c.title=phrase(input);save()}if(!c.source){notes.focus();return}const type=$('#questionType').value,difficulty=$('#difficulty').value,count=+$('#questionCount').value,ss=selectTopics(c.source,count);if(!ss.length){add({kind:'answer',text:'I could not find enough readable study content. Try uploading a text-based document or paste the notes.'});return}add({kind:'user',text:`Make me a ${difficulty.toLowerCase()} ${type} quiz.`});add({kind:'quiz',type,difficulty,count:Math.min(count,ss.length),questions:ss.map((s,i)=>question(s,i,type))});notes.value='';renderAll()}
function submit(){const text=notes.value.trim(),c=active();if(!text)return quiz();if(c.source&&(/\?$/.test(text)||/^(what|why|how|when|where|who|explain|define|summari[sz]e|tell me)/i.test(text))){add({kind:'user',text});add({kind:'answer',text:reply(text)});notes.value='';return}if(!c.source){c.source=text;c.title=phrase(text);save();notes.value=''}quiz()}
function renderHistory(){const filter=$('#historySearch').value.toLowerCase();$('#chatHistory').innerHTML=chats.filter(c=>c.title.toLowerCase().includes(filter)||c.source.toLowerCase().includes(filter)).map(c=>`<button class="history-item ${c.id===activeId?'active':''}" data-id="${c.id}" title="${esc(c.title)}">${esc(c.title)}</button>`).join('')||'<span class="file-name">No matching chats</span>';$$('.history-item').forEach(b=>b.onclick=()=>{activeId=b.dataset.id;renderAll()})}
function renderAll(){const c=active();$('#noteStatus').textContent=c.source?`${c.source.split(/\s+/).length} words saved`:'No notes added';$('#fileName').textContent=c.source?'Notes saved for this study chat':'Click to choose, or drag a PDF, Word, PowerPoint, or text file here';renderHistory();renderConversation()}
async function pdfText(f){const p=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const d=await p.getDocument({data:await f.arrayBuffer()}).promise;return(await Promise.all(Array.from({length:d.numPages},async(_,i)=>(await(await d.getPage(i+1)).getTextContent()).items.map(x=>x.str).join(' ')))).join('\n')}
async function fileText(f){const e=f.name.split('.').pop().toLowerCase();if(e==='pdf')return pdfText(f);if(e==='docx')return(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value;if(e==='pptx'){const z=await JSZip.loadAsync(await f.arrayBuffer()),names=Object.keys(z.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n));return(await Promise.all(names.map(async n=>[...(await z.files[n].async('text')).matchAll(/<a:t>([\s\S]*?)<\/a:t>/g)].map(x=>x[1]).join(' ')))).join('\n')}if(['txt','md'].includes(e))return f.text();throw Error('Use PDF, DOCX, PPTX, TXT, or Markdown. Convert old .doc/.ppt files first.')}
async function loadFile(f){if(!f)return;$('#fileName').textContent=`Reading ${f.name}…`;try{const t=await fileText(f);if(!t.trim())throw Error('No selectable text was found in this file.');const c=active();c.source=t.trim();c.title=f.name;save();notes.value='';renderAll()}catch(e){$('#fileName').textContent=e.message;$('#fileInput').value=''}}
$('#generate').onclick=submit;notes.onkeydown=e=>{if(e.ctrlKey&&e.key==='Enter')submit()};$('#newChat').onclick=createChat;$('#historySearch').oninput=renderHistory;$('#uploadButton').onclick=e=>{e.stopPropagation();$('#fileInput').click()};$('#fileInput').onchange=e=>loadFile(e.target.files[0]);const dz=$('#dropZone');dz.onclick=()=>$('#fileInput').click();['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.ondrop=e=>loadFile(e.dataTransfer.files[0]);dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#fileInput').click()}};if(!chats.length)createChat();else renderAll();
